spring.application.name=SIA

# 🔥 DESACTIVAR COMPLETAMENTE BASE DE DATOS
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Puerto para Render
server.port=${PORT:8080}

# ❌ DESACTIVAR JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Thymeleaf
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logs básicos (menos ruido)
logging.level.org.springframework=INFO
logging.level.com.example=DEBUG

# Errores
server.error.whitelabel.enabled=false
server.error.path=/error

# Archivos
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Email (déjalo si lo usas)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}
spring.mail.password=${MAIL_PASS}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true